### ISSUE TITLE
RangeError: Start offset undefined is outside the bounds of the buffer

### ISSUE THREAD

**Issue by Makeshift** [Bnaya/objectbuffer#175]
First of all, thank you for this project, it's allowed me to do some insanely cool things.

Secondly, I appear to have encountered an issue trying to share data between workers with a fairly large dataset.

It seems if the dataset goes above 4GB in size, I get this error:

```
Exception has occurred: RangeError: Start offset undefined is outside the bounds of the buffer
  at new Uint8Array (<anonymous>)
    at /home/connor/WebstormProjects/wsl/zenbot/node_modules/@bnaya/objectbuffer/dist/objectbuffer.umd.js:2761:108
    at Array.map (<anonymous>)
    at createHeap (/home/connor/WebstormProjects/wsl/zenbot/node_modules/@bnaya/objectbuffer/dist/objectbuffer.umd.js:2761:79)
    at allocatorInit (/home/connor/WebstormProjects/wsl/zenbot/node_modules/@bnaya/objectbuffer/dist/objectbuffer.umd.js:2813:10)
    at new TransactionalAllocator (/home/connor/WebstormProjects/wsl/zenbot/node_modules/@bnaya/objectbuffer/dist/objectbuffer.umd.js:3465:31)
    at createObjectBuffer (/home/connor/WebstormProjects/wsl/zenbot/node_modules/@bnaya/objectbuffer/dist/objectbuffer.umd.js:3706:23)
    at /home/connor/WebstormProjects/wsl/zenbot/lib/backtester.js:75:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

For example, `createObjectBuffer(4292116528, dataset)` works fine, whereas `createObjectBuffer(4630484096, dataset)` fails with the above exception.

The dataset in question is of the format: 
```
{
  data: [...2305900 objects]
}
```

I couldn't find any documentation online stating that ArrayBuffers are limited to 4GB. I don't mind splitting the dataset into multiple buffers, but was curious if you knew why this seemed to be the case.

**Comment by Makeshift** [comment]
[This link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length) claims the maximum on x64 is 8GB, so I was surprised to see a 4GB limit.

**Comment by Makeshift** [comment]
Nevermind, found my answer in the [implementation docs](https://github.com/Bnaya/objectbuffer/blob/0310a14359fb11d00fd503d2154079a1d2ef5a27/docs/implementationDetails.md).

**Comment by Bnaya** [comment]
I'm happy to see that someone is really using the library :)
I would love to hear more about your use case
